### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Ianleeclark** [bcopeland/python-radiotap#2]
Hey, would you mind adding a license onto this? If you don't, others may not be able to use it due to copyright laws: https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

I personally prefer the MIT license, but there's also a comparison of the advantages/disadvantages between different open source licenses here: https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by bcopeland** [comment]
On Wed, Nov 18, 2015 at 08:09:14AM -0800, Ian C wrote:

> Hey, would you mind adding a license onto this? If you don't, others may not be able to use it due to copyright laws: https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license
> 
> I personally prefer the MIT license, but there's also a comparison of the advantages/disadvantages between different open source licenses here: https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

Sure, will do.  MIT is fine with me for this.

## 

Bob Copeland %% http://bobcopeland.com/

**Comment by bcopeland** [comment]
License added.  Also, pushed this repo to the official radiotap project over here: https://github.com/radiotap/python-radiotap
