### ISSUE TITLE
dbm_antsignal is buggy

### ISSUE THREAD

**Issue by jnmbk** [bcopeland/python-radiotap#3]
Hi,

I observed that the dbm_antsignal is returning the same value (160) every time which is impossible. Adding 4 to its offset seems to fix it for me and returns correct value. Sorry, I didn't have time to find out what the real cause is.

As far as I can see; I don't have the "fhss" flag set but your library is pretending that it is set. There might be something wrong with the flag checking.

**Comment by bcopeland** [comment]
Do you have a sample pcap file I can test with?  You could just export a couple of packets that show the issue.

**Comment by jnmbk** [comment]
I couldn't reproduce this with a pcap file. I was using live capture with pcappy when it happened. Live capture must have been causing some corruption in the packets.
